// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCOtvGLhjFuKcnDUZ3T2YNYUCKFu9Em2s',
    appId: '1:800345266802:web:2feb4c33c40e49d35500eb',
    messagingSenderId: '800345266802',
    projectId: 'cloud-contacts-d09b4',
    authDomain: 'cloud-contacts-d09b4.firebaseapp.com',
    storageBucket: 'cloud-contacts-d09b4.firebasestorage.app',
    measurementId: 'G-5J3XR349VN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCrYZCKtEHQcNzc-aUokVWXllYo7JOJ_8',
    appId: '1:800345266802:android:9f725b5c0cf2639a5500eb',
    messagingSenderId: '800345266802',
    projectId: 'cloud-contacts-d09b4',
    storageBucket: 'cloud-contacts-d09b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHNP8oG1K8FuDeTrkl7iA1U_M0J1JR2Vk',
    appId: '1:800345266802:ios:875745661860879d5500eb',
    messagingSenderId: '800345266802',
    projectId: 'cloud-contacts-d09b4',
    storageBucket: 'cloud-contacts-d09b4.firebasestorage.app',
    iosBundleId: 'com.example.cloudContacts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHNP8oG1K8FuDeTrkl7iA1U_M0J1JR2Vk',
    appId: '1:800345266802:ios:875745661860879d5500eb',
    messagingSenderId: '800345266802',
    projectId: 'cloud-contacts-d09b4',
    storageBucket: 'cloud-contacts-d09b4.firebasestorage.app',
    iosBundleId: 'com.example.cloudContacts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCOtvGLhjFuKcnDUZ3T2YNYUCKFu9Em2s',
    appId: '1:800345266802:web:77c30d32af866ffc5500eb',
    messagingSenderId: '800345266802',
    projectId: 'cloud-contacts-d09b4',
    authDomain: 'cloud-contacts-d09b4.firebaseapp.com',
    storageBucket: 'cloud-contacts-d09b4.firebasestorage.app',
    measurementId: 'G-6QT06FLDBL',
  );

}